app/main/routes.py
#TODO
#   upload users via csv
#   consider use of material css/Bulma or tailwind
#   change input box to prepend +254
#   inlude a pandas report on dashboard page
#   include email address in user accounts data
#   generate PDF with details of airtime and sent to user's email
#


from flask import render_template, Blueprint, flash, redirect, url_for
from app import app, db
from app.main.forms import SendAirtime, AddNumber
from app.models import TelephoneNumbers, AirtimeSent
from app.users.utilities import airtime_mail, current_date
from flask_login import login_required
import pandas as pd
import africastalking
import arrow


main = Blueprint('main', __name__)

username = app.config['AT_USERNAME']
apikey = app.config['AT_API_KEY']


@app.template_filter('round_off_balance')
def round_off_filter(value):
    rounded_value = round(value)
    return rounded_value


@app.template_filter('human_time')
def human_time_filter(sent_time):
    human_time = arrow.get(sent_time)
    show_time = human_time.humanize()
    return show_time


@app.template_filter('format_time')
def format_time_filter(db_time):
    saved_time = arrow.get(db_time)
    formatted_time = saved_time.to('Africa/Nairobi').format('YYYY-MM-DD HH:mm')
    return formatted_time


@app.context_processor
def get_balance():
    africastalking.initialize(username, apikey)
    application = africastalking.Application
    results = application.fetch_application_data()
    credit_balance = results['UserData']['balance']
    final_float = float(credit_balance.strip('KES '))

    return dict(final_float=final_float)


@main.route('/send_airtime', methods=['POST', 'GET'])
@login_required
def send_airtime():
    load_balance = get_balance()
    starting_balance = load_balance.get('final_float') # airtime balance when app loads

    form = SendAirtime()
    africastalking.initialize(username, apikey)

    airtime = africastalking.Airtime
    application = africastalking.Application

    if form.validate_on_submit():
        to = form.to.data
        saved_tel = to.alias
        value = form.airtime_value.data

        try:
            airtime.send(to, value, currency_code=app.config['AT_CURRENCY_CODE'])
            res = application.fetch_application_data()

            my_balance = res['UserData']['balance']
            my_balance_float = float(my_balance.strip('KES '))

            if my_balance_float < starting_balance:
                save_airtime = AirtimeSent(amount_sent=value, sent_to=saved_tel)
                db.session.add(save_airtime)
                db.session.commit()
                mail_date = current_date()

                flash(f'You have successfully send airtime worth KShs: {value} to {to}! Your balance is {my_balance}',
                      'success')
                airtime_mail(value, saved_tel, mail_date, my_balance)
            else:
                flash('Airtime transfer failed, please try again after a few minutes', 'danger')

        except Exception as e:
            pass

    return render_template('send_airtime.html', form=form)


@main.route('/accounts/', methods=['POST', 'GET'])
@login_required
def telephones():
    numbers = TelephoneNumbers.query.all()
    return render_template('telephones.html', numbers=numbers)


@main.route('/accounts/<int:number_id>/', methods=['GET'])
@login_required
def number(number_id):
    number = TelephoneNumbers.query.get_or_404(number_id)
    return render_template('number.html', title=number.tel, number=number)


@main.route('/accounts/<int:delete_number_id>/delete', methods=['POST', 'GET'])
@login_required
def delete_number(delete_number_id):
    number_to_delete = TelephoneNumbers.query.get_or_404(delete_number_id)
    db.session.delete(number_to_delete)
    db.session.commit()
    flash(f'{number_to_delete} deleted! ', 'success')
    return redirect(url_for('main.telephones'))


@main.route('/record/<int:record_id>/delete', methods=['POST', 'GET'])
@login_required
def delete_record(record_id):
    record_to_delete = AirtimeSent.query.get_or_404(record_id)
    db.session.delete(record_to_delete)
    db.session.commit()
    flash(f'{record_to_delete} deleted! ', 'success')
    return redirect(url_for('main.get_records'))


@main.route('/new', methods=['POST', 'GET'])
@login_required
def new_number():
    form = AddNumber()
    if form.validate_on_submit():
        new_number = TelephoneNumbers(tel=form.telephone.data, alias=form.name.data)
        db.session.add(new_number)
        db.session.commit()
        flash(f'{new_number} added successfully.', 'success')
        return redirect(url_for('main.telephones'))
    return render_template('new.html', form=form)


@main.route('/dashboard', methods=['GET'])
@login_required
def get_records():
    records = AirtimeSent.query.all()
    data = db.session.execute("SELECT * FROM airtime_sent").fetchall()
    dataframe = pd.DataFrame(data, columns=['ID', 'Amount', 'Name', 'Time'])
    df = dataframe.drop(columns=['Time', 'ID'], index=None)
    total_per_user = df.groupby(['Name'], as_index=False,).sum().sort_values(by=['Amount'], ascending=False)
    with_name_index = total_per_user.set_index('Name')
    labels = total_per_user['Name'].values.tolist()
    values = total_per_user['Amount'].values.tolist()

    user_table = with_name_index.to_html(classes=['table', 'table-bordered', 'table-striped', 'table-hover'])

    return render_template('dashboard.html', records=records, user_table=user_table, values=values, labels=labels)

app/users/routes.py
from flask import Blueprint, redirect, request, flash, render_template, url_for
from flask_login import current_user, login_user, logout_user, login_required
from app.users.forms import LoginForm, Registration, RequestResetForm, ResetPassword
from app import db, bcrypt
from app.models import User
from app.users.utilities import send_reset_email

users = Blueprint('users', __name__)


@users.route('/', methods=['POST', 'GET'])
@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.send_airtime'))
    login_form = LoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(username=login_form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, login_form.password.data):
            login_user(user)
            flash(f'Welcome {user.username}!', 'success')
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('users.login'))
        else:
            flash('Login unsuccessful, please check your credentials!', 'danger')
    return render_template('login.html', loginform=login_form)



"""
@users.route('/register', methods=['POST', 'GET'])
#@login_required   #Authorized IT personnel will create account.
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    registration_form = Registration()
    if registration_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(registration_form.password.data).decode('utf-8')
        user = User(username=registration_form.username.data,
                    email=registration_form.email.data, password=hashed_password
                    )
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', registration_form=registration_form)

"""


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        token = user.get_reset_token()
        send_reset_email(user, 'mail/reset', token=token, username=user.username)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPassword()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated. You can now login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{ super() }}

<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
<link href="//cdn.materialdesignicons.com/3.6.95/css/materialdesignicons.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<link href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css" rel="stylesheet" />


{% endblock %}

{% block scripts %}
{{ super() }}

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<script>

    $(document).ready(function () {
        $('#table_id').DataTable({
            dom: 'Bfrtip',
            buttons: [
                {
                    extend: 'pdf',
                    title: 'Airtime Spend Summary',

                },
                'csv', 'excel', 'print'
            ],
            "pageLength": 5,
            "order": [[2, "desc"]],
            "footerCallback": function (row, data, start, end, display) {
                var api = this.api(), data;

                var intVal = function (i) {
                    return typeof i === 'string' ?
                        i.replace(/[\$,]/g, '') * 1 :
                        typeof i === 'number' ?
                            i : 0;
                };
                total = api
                    .column(1)
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0);

                pageTotal = api
                    .column(1, { page: 'current' })
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0);

                $(api.column(1).footer()).html(
                    'KShs ' + pageTotal + ' [ KShs ' + total + ' Running Total ]'
                );
            }
        });
    });
</script>

<script>
    var data = [{
        values: {{ values }},
    labels: { { labels | safe } },
    type: 'pie'
    }];

    var layout = {
        title: '% Spend Per Account',
    };

    Plotly.newPlot('myDiv', data, layout, { responsive: true });
</script>

<script src="{{ url_for('static', filename = 'js/main.js') }}"></script>


{% endblock %}

{% block title %} Airtime Purchase & Distribution - Tazama Data {% endblock %}

{% block navbar %}

<div class="navbar navbar-inverse bg-red" role="navigation">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="{{ url_for('users.login') }}" class="navbar-brand">Tazama Data Airtime App</a>
                </div>

            </div>
            <div class="col-md-8">
                <ul class="nav navbar-nav navbar-collapse collapse pull-right-lg">

                    {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('main.telephones') }}"><i class="mdi mdi-account-badge-horizontal-outline"
                                aria-hidden="true"></i> Accounts</a></li>
                    <li><a href="{{ url_for('main.send_airtime') }}"><i class="mdi mdi-cellphone"
                                aria-hidden="true"></i> Airtime</a>
                    </li>

                    <li><a href="{{ url_for('main.get_records') }}"><i class="mdi mdi-view-dashboard"
                                aria-hidden="true"></i>
                            Dashboard</a>
                    </li>
                    <li><a href="{{ url_for('users.logout') }}"><i class="mdi mdi-login" aria-hidden="true"></i>
                            Logout</a></li>




                    <li> <a class="" href="#">
                            {% if final_float < 150 %} <span class="balance_low blink-1">Bal: KShs {{ final_float |
                                round_off_balance }}</span>


                                {% else %}
                                <span class="balance ">Bal: KShs {{ final_float | round_off_balance }}</span>
                                {% endif %}





                        </a></li>





                    {% else %}
                    <li class="highlight"><a href="{{ url_for('users.login') }}"><i class="mdi mdi-login"
                                aria-hidden="true"></i>
                            Login</a>
                    </li>
                    <li class="highlight"><a href="{{ url_for('users.register') }}"><i class="mdi mdi-account-plus"
                                aria-hidden="true"></i>
                            Register</a>
                    </li>

                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block content %}

<div class="container main-body">
    <div class="row">
        <div class="col-md-12">
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            {% block maincontent %}{% endblock %}
        </div>

    </div>
    <div class="footer navbar-fixed-bottom m4 ">
        <div class="container">&copy; 2023. Tazama Data</div>
    </div>
</div>

{% endblock %}

app/templates/dashboard.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}


{% block styles %}
    {{ super() }}

<link rel="stylesheet" href="{{ url_for('static', filename='css/tipr.css') }}">

{% endblock %}

{% block scripts %}
{{ super() }}

<script src="{{ url_for('static', filename = 'js/tipr.min.js') }}"></script>

<script>
$(document).ready(function() {
     $('.tip').tipr();
});
</script>

{% endblock %}

{% block maincontent %}

<div class="container">


    <div class="row">
        <div class="col-md-6">
                <table id="table_id" class="table table-hover table-striped table-bordered ">
                    <thead>
                    <tr>
                        <th>To:</th>
                        <th>Amount</th>
                        <th>When</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tr>
                        {% for record in records %}
                            <td>{{ record.sent_to }}</td>
                            <td>{{ record.amount_sent }}</td>
                           <td><span class="tip" data-tip="{{ record.date_sent | human_time }}">{{ record.date_sent | format_time }}</span></td>
                            <td class="delete-column">
                                <button class="btn btn-danger " data-toggle="modal"
                                        data-target="#DeleteModal{{ record.id }}"><i class="mdi mdi-delete-outline"
                                                                                     aria-hidden="true"></i>
                                </button>

                                {#                        <input type="checkbox" name="do_delete" value="{{ record.id }}">#}
                            </td>
                            </tr>


                            <div id="DeleteModal{{ record.id }}" class="modal fade" role="dialog">
                                <div class="modal-dialog">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                            <h4 class="modal-title">Delete Airtime record: {{ record.sent_to }} -
                                                KShs {{ record.amount_sent }}</h4>
                                        </div>
                                        <div class="modal-footer">
                                            <ul class="footer-links">
                                                <li>
                                                    <button type="button" class="btn btn-primary" data-dismiss="modal">
                                                        Close
                                                    </button>
                                                </li>
                                                <li>
                                                    <a class="btn btn-danger rounded-0"
                                                       href="{{ url_for('main.delete_record', record_id=record.id) }}">Delete</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    <tfoot>
                    <tr>
                        <th colspan="4" style="text-align:right">Total:</th>
                    </tr>
                    </tfoot>
                </table>
        </div>

        <div class="col-md-6">
            <div class="panel panel-default">

                <div class="panel-body">
                    <div id="myDiv"></div>
                </div>
            </div>
        </div>
</div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block maincontent %}

    {% if current_user.is_authenticated %}

    {% if final_float < 150 %}

        <div class="well bg-balance">
            Your balance is running low. Please top up.
        </div>

    {% endif %}

    {% endif %}

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block maincontent %}

    <div class="container">
            <div class="row well">


                <div class="col-md-6 col-md-offset-3  h-150">


                    {{ wtf.quick_form(loginform, button_map={'submit':'primary'}) }}
                    <small><a href="{{ url_for('users.reset_request') }}">Forgot Password?</a></small>
                    <br/>

                </div>
            </div>
        </div>
{% endblock %}

app/templates/new.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block maincontent %}

    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            {{ wtf.quick_form(form, extra_classes='newform', button_map={'submit':'primary'}) }}
        </div>

        {{ e }}

    </div>
{% endblock %}

app/templates/number.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block maincontent %}

    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            {{ number.tel }}
        </div>

        {{ e }}

    </div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block maincontent %}
    <div class="container register">
        <div class="row well">
            <div class="col-md-6 col-md-offset-3 ">
                {{ wtf.quick_form(registration_form, button_map={'submit':'primary'}) }}
            </div>


        </div>
    </div>

{% endblock %}

app/templates/reset_request.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %} {{ title }} {% endblock %}

{% block maincontent %}
    <p></p>
    <div class="update col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">Reset Password</div>
            <div class="panel-body">
                {{ wtf.quick_form(form, extra_classes='myform', button_map={'submit':'primary rounded-4 p-15'}) }}
            </div>
        </div>
    </div>

{% endblock %}

app/templates/reset_token.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %} {{ title }} {% endblock %}

{% block maincontent %}
    <p></p>
    <div class="update col-md-6 col-md-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">Reset Password</div>
            <div class="panel-body">
                {{ wtf.quick_form(form, extra_classes='myform', button_map={'submit':'primary rounded-2 p-15'}) }}
            </div>
        </div>
    </div>

{% endblock %}

app/templates/send_airtime.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block maincontent %}

    <div class="container">
        <div class="col-md-6 col-md-offset-3">
            {{ wtf.quick_form(form, extra_classes='airtimeform', button_map={'submit_send_airtime':'primary'}) }}
        </div>
        {{ e }}
    </div>

{% endblock %}

app/templates/telephone.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block maincontent %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            {{ telephone.tel }}
        </div>

        {{ e }}

    </div>
{% endblock %}

app/templates/telephones.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}


{% block maincontent %}

    <div class="container">

      {% if current_user.is_authenticated %}

    {% if final_float < 150 %}

        <div class="well bg-balance">
            Your balance is running low. Please top up.
        </div>

    {% endif %}

    {% endif %}


        <a class="btn btn-success rounded-2 m-4" href="{{ url_for('main.new_number') }}">Add Number</a>

       <div class="table-responsive">
            <table class="table table-hover table-striped table-bordered ">
                <thead>
                <tr>
                    <th>Assigned Name</th>
                    <th>Telephone Number</th>
                    <th>Delete</th>
                </tr>
                </thead>
            {% for number in numbers %}
                <tr>
                    <td>{{ number.alias }}</td>
                    <td>{{ number.tel }}</td>
                    <td class="delete-column">
                        <button class="btn btn-danger" data-toggle="modal"
                                    data-target="#DeleteModal{{ number.id }}"><i class="mdi mdi-delete-outline" aria-hidden="true"></i>
                        </button>
                    </td>
                </tr>
                       <div id="DeleteModal{{ number.id }}" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Delete Telephone #: {{ number.tel }} - {{ number.alias }}</h4>
                                    </div>
                                    <div class="modal-footer">
                                        <ul class="footer-links">
                                            <li>
                                                <button type="button" class="btn btn-primary" data-dismiss="modal">
                                                    Close
                                                </button>
                                            </li>
                                            <li>
                                                <a class="btn btn-danger rounded-0" href="{{ url_for('main.delete_number', delete_number_id=number.id) }}">Delete</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
            {% endfor %}
            </table>
       </div>
    </div>

{% endblock %}